"""生成独立包快照所需契约；只维护 flows/contracts.py。"""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent
source = root / 'flows/contracts.py'
target = root / 'packages/example/contracts.py'
expected = '# Generated by sync_contracts.py; DO NOT EDIT.\n' + source.read_text()
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
if parser.parse_args().check:
    assert target.read_text() == expected, '请运行 sync_contracts.py 同步契约'
else:
    target.write_text(expected)
