"""从已验收计分/契约权威源生成独立单文件分发块；--check 检查漂移。"""
import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'source'
HEADER = '# Generated by generate_blocks.py; DO NOT EDIT.\n'
contracts = ast.parse((SOURCE / 'contracts.py').read_text())
contracts.body = [n for n in contracts.body if not isinstance(n, ast.FunctionDef) or n.name != 'validate_report']
common = ast.unparse(contracts) + '\nfrom agent_platform.blocks import block\n'
preprocessing = ast.parse((SOURCE / 'preprocessing.py').read_text())
prepared = ast.unparse(next(n for n in preprocessing.body if isinstance(n, ast.ClassDef))) + '\n'
clean_parts = []
for node in preprocessing.body:
    if isinstance(node, ast.ImportFrom) and node.level:
        continue
    if isinstance(node, ast.ClassDef):
        continue
    if isinstance(node, ast.FunctionDef) and node.name == 'preprocess':
        node.name = 'run'
        node.decorator_list = ast.parse("@block(id='similarity-clean', version='1.0.0', name='查重清洗', description='NFC、换行与水平空白规范；拒绝清洗后空文本', dependencies=['pydantic-core>=2,<3'])\ndef run(): pass").body[0].decorator_list
    clean_parts.append(node)
clean = ast.unparse(ast.Module(body=clean_parts, type_ignores=[])) + '\n'
score_tree = ast.parse((SOURCE / 'scoring.py').read_text())
score_fn = next(n for n in score_tree.body if isinstance(n, ast.FunctionDef))
score_fn.name = 'run'
score = "\nfrom collections import defaultdict\n@block(id='similarity-score', version='1.0.0', name='查重计分', description='paragraph-exact-v1：目标段落精确匹配与字符比例', dependencies=['pydantic-core>=2,<3'])\n" + ast.unparse(score_fn) + '\n'
adapt = '''
@block(id='similarity-adapt', version='1.0.0', name='语义输入适配', description='显式将清洗段落组装为语义包文本输入', dependencies=['pydantic-core>=2,<3'])
def run(value: PreparedTexts) -> SimilarityInput:
    return SimilarityInput(target_text='\\n'.join(value.target_paragraphs), comparison_texts=['\\n'.join(parts) for parts in value.comparison_paragraphs])
'''
# 传输输入声明结构约束；业务函数再用权威报告模型执行跨字段校验。
# 不把来源不同的自定义 Python 校验器误称为可静态等价。
wire_tree = ast.parse((SOURCE / 'contracts.py').read_text())
classes = {n.name for n in wire_tree.body if isinstance(n, ast.ClassDef)}
wire_tree.body = [n for n in wire_tree.body if isinstance(n, ast.ClassDef)]
class Wire(ast.NodeTransformer):
    def visit_ClassDef(self, node):
        node.name = 'Wire' + node.name
        node.body = [n for n in node.body if not isinstance(n, ast.FunctionDef)]
        return self.generic_visit(node)
    def visit_Name(self, node):
        if node.id in classes: node.id = 'Wire' + node.id
        return node
    def visit_Call(self, node):
        node.keywords = [k for k in node.keywords if k.arg != 'allow_inf_nan']
        return self.generic_visit(node)
wire = ast.unparse(Wire().visit(wire_tree))
assembly = '''
class AssemblyInput(StrictModel):
    request: SimilarityInput
    quantitative: WireQuantitativeReport
    qualitative: WireQualitativeReport

@block(id='similarity-assemble', version='1.0.0', name='查重报告组装', description='显式引用定量、定性与原请求，校验完整覆盖后返回双报告', dependencies=['pydantic-core>=2,<3'])
def run(value: AssemblyInput) -> SimilarityReport:
    return SimilarityReport.model_validate({'quantitative': value.quantitative.model_dump(by_alias=True), 'qualitative': value.qualitative.model_dump(by_alias=True)}, context={'comparison_count': len(value.request.comparison_texts)})
'''
files = {'clean':common+prepared+clean, 'score':common+prepared+score, 'adapt':common+prepared+adapt, 'assemble':common+wire+assembly}
parser = argparse.ArgumentParser();parser.add_argument('--check', action='store_true');check=parser.parse_args().check
for name, source in files.items():
    path = ROOT / 'blocks' / (name + '.py'); expected = HEADER + source
    if check: assert path.read_text() == expected, f'请重新生成 {name}'
    else: path.write_text(expected)
