"""从已验收计分/契约权威源生成独立单文件分发块；--check 检查漂移。"""
import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'instance'
HEADER = '# Generated by generate_blocks.py; DO NOT EDIT.\n'
contracts = ast.parse((SOURCE / 'contracts.py').read_text())
contracts.body = [n for n in contracts.body if not isinstance(n, ast.FunctionDef) or n.name != 'validate_report']
common = ast.unparse(contracts) + '\nfrom agent_platform.blocks import block\n'
prepared = '''
class PreparedTexts(StrictModel):
    target_paragraphs: list[NonemptyText] = Field(min_length=1)
    comparison_paragraphs: list[list[NonemptyText]] = Field(min_length=1)
'''
clean = '''
import re
import unicodedata
from agent_platform.contracts.errors import ErrorResponse, PlatformError
@block(id='similarity-clean', version='1.0.0', name='查重清洗', description='NFC、换行与水平空白规范；拒绝清洗后空文本', dependencies=['pydantic-core>=2,<3'])
def run(value: SimilarityInput) -> PreparedTexts:
    result = []
    for index, text in enumerate([value.target_text, *value.comparison_texts]):
        text = unicodedata.normalize('NFC', text.replace('\\r\\n', '\\n').replace('\\r', '\\n'))
        parts = [clean for line in text.split('\\n') if (clean := re.sub(r'[^\\S\\r\\n\\v\\f\\x85\\u2028\\u2029]+', ' ', line).strip())]
        if not parts:
            raise PlatformError(ErrorResponse(code='CONTRACT_VALIDATION_ERROR', stage='similarity.preprocess', message='清洗后文本不得为空', field_path=['targetText'] if index == 0 else ['comparisonTexts', index-1]), 422)
        result.append(parts)
    return PreparedTexts(target_paragraphs=result[0], comparison_paragraphs=result[1:])
'''
score_tree = ast.parse((SOURCE / 'scoring.py').read_text())
score_fn = next(n for n in score_tree.body if isinstance(n, ast.FunctionDef))
score_fn.name = 'run'
score = "\nfrom collections import defaultdict\n@block(id='similarity-score', version='1.0.0', name='查重计分', description='paragraph-exact-v1：目标段落精确匹配与字符比例', dependencies=['pydantic-core>=2,<3'])\n" + ast.unparse(score_fn) + '\n'
adapt = '''
@block(id='similarity-adapt', version='1.0.0', name='语义输入适配', description='显式将清洗段落组装为语义包文本输入', dependencies=['pydantic-core>=2,<3'])
def run(value: PreparedTexts) -> SimilarityInput:
    return SimilarityInput(target_text='\\n'.join(value.target_paragraphs), comparison_texts=['\\n'.join(parts) for parts in value.comparison_paragraphs])
'''
# 传输输入声明结构约束；业务函数再用权威报告模型执行跨字段校验。
# 不把来源不同的自定义 Python 校验器误称为可静态等价。
wire_tree = ast.parse((SOURCE / 'contracts.py').read_text())
classes = {n.name for n in wire_tree.body if isinstance(n, ast.ClassDef)}
wire_tree.body = [n for n in wire_tree.body if isinstance(n, ast.ClassDef)]
class Wire(ast.NodeTransformer):
    def visit_ClassDef(self, node):
        node.name = 'Wire' + node.name
        node.body = [n for n in node.body if not isinstance(n, ast.FunctionDef)]
        return self.generic_visit(node)
    def visit_Name(self, node):
        if node.id in classes: node.id = 'Wire' + node.id
        return node
    def visit_Call(self, node):
        node.keywords = [k for k in node.keywords if k.arg != 'allow_inf_nan']
        return self.generic_visit(node)
wire = ast.unparse(Wire().visit(wire_tree))
assembly = '''
class AssemblyInput(StrictModel):
    request: SimilarityInput
    quantitative: WireQuantitativeReport
    qualitative: WireQualitativeReport

@block(id='similarity-assemble', version='1.0.0', name='查重报告组装', description='显式引用定量、定性与原请求，校验完整覆盖后返回双报告', dependencies=['pydantic-core>=2,<3'])
def run(value: AssemblyInput) -> SimilarityReport:
    return SimilarityReport.model_validate({'quantitative': value.quantitative.model_dump(by_alias=True), 'qualitative': value.qualitative.model_dump(by_alias=True)}, context={'comparison_count': len(value.request.comparison_texts)})
'''
files = {'clean':common+prepared+clean, 'score':common+prepared+score, 'adapt':common+prepared+adapt, 'assemble':common+wire+assembly}
parser = argparse.ArgumentParser();parser.add_argument('--check', action='store_true');check=parser.parse_args().check
for name, source in files.items():
    path = ROOT / 'blocks' / (name + '.py'); expected = HEADER + source
    if check: assert path.read_text() == expected, f'请重新生成 {name}'
    else: path.write_text(expected)
