const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('agentPlatform', Object.freeze({
  validateFlowPorts: (body) => ipcRenderer.invoke('platform:validateFlowPorts', body),
  validateFlowNode: (body) => ipcRenderer.invoke('platform:validateFlowNode', body),
  createDraft: (body) => ipcRenderer.invoke('platform:createDraft', body),
  listDrafts: () => ipcRenderer.invoke('platform:listDrafts'),
  getDraft: (id) => ipcRenderer.invoke('platform:getDraft', id),
  updateDraft: (id, body) => ipcRenderer.invoke('platform:updateDraft', id, body),
  validateDraft: (id) => ipcRenderer.invoke('platform:validateDraft', id),
  validateFlow: (body) => ipcRenderer.invoke('platform:validateFlow', body),
  loadResource: (body) => ipcRenderer.invoke('platform:loadResource', body),
  listResources: () => ipcRenderer.invoke('platform:listResources'),
  getResource: (id) => ipcRenderer.invoke('platform:getResource', id),
  connectionModels: (body) => ipcRenderer.invoke('platform:connectionModels', body),
  testConnection: (body) => ipcRenderer.invoke('platform:testConnection', body),
  cancelRun: (id) => ipcRenderer.invoke('platform:cancelRun', id),
  submitRun: (body) => ipcRenderer.invoke('platform:submitRun', body),
  getRun: (id) => ipcRenderer.invoke('platform:getRun', id),
  getRunResult: (id) => ipcRenderer.invoke('platform:getRunResult', id),
  listEnvironments: () => ipcRenderer.invoke('platform:listEnvironments'),
  createEnvironment: (body) => ipcRenderer.invoke('platform:createEnvironment', body),
  updateEnvironment: (id, body) => ipcRenderer.invoke('platform:updateEnvironment', id, body),
  loadDefinition: (body) => ipcRenderer.invoke('platform:loadDefinition', body),
  listServices: () => ipcRenderer.invoke('platform:listServices'),
  createService: (body) => ipcRenderer.invoke('platform:createService', body),
  saveServiceVersion: (id, body) => ipcRenderer.invoke('platform:saveServiceVersion', id, body),
  serviceSchema: (id) => ipcRenderer.invoke('platform:serviceSchema', id),
  serviceHistory: (id) => ipcRenderer.invoke('platform:serviceHistory', id),
  activateService: (id, instanceId) => ipcRenderer.invoke('platform:activateService', id, instanceId),
  health: () => ipcRenderer.invoke('platform:health'),
}));
