# Generated by sync_contracts.py; DO NOT EDIT.
"""查重契约权威来源；语义包中的 contracts.py 由同步脚本生成。"""
from typing import Annotated, Literal
from pydantic import Field, ValidationInfo, model_validator
from agent_platform.contracts.base import StrictModel

Index = Annotated[int, Field(ge=0)]
NonemptyText = Annotated[str, Field(min_length=1)]


class SimilarityInput(StrictModel):
    target_text: str
    comparison_texts: list[str] = Field(min_length=1)


def aligned(items, count):
    indices = [item.comparison_index for item in items]
    if len(indices) != count or set(indices) != set(range(count)):
        raise ValueError('comparisonIndex 必须唯一且覆盖全部对照索引')


class ParagraphMatch(StrictModel):
    target_paragraph_index: Index
    comparison_paragraph_indices: list[Index] = Field(min_length=1)

    @model_validator(mode='after')
    def unique_indices(self):
        if len(set(self.comparison_paragraph_indices)) != len(self.comparison_paragraph_indices):
            raise ValueError('对照段落索引不得重复')
        return self


class QuantitativeItem(StrictModel):
    comparison_index: Index
    similarity: float = Field(ge=0, le=1, allow_inf_nan=False)
    matched_target_characters: int = Field(ge=0)
    total_target_characters: int = Field(gt=0)
    matches: list[ParagraphMatch]

    @model_validator(mode='after')
    def valid_counts(self):
        if self.matched_target_characters > self.total_target_characters:
            raise ValueError('匹配字符数不得超过目标字符数')
        positions = [match.target_paragraph_index for match in self.matches]
        if len(set(positions)) != len(positions):
            raise ValueError('每个目标段落位置最多匹配一次')
        return self


class QuantitativeReport(StrictModel):
    method: Literal['paragraph-exact-v1']
    items: list[QuantitativeItem] = Field(min_length=1)

    @model_validator(mode='after')
    def indices(self, info: ValidationInfo):
        aligned(self.items, (info.context or {}).get('comparison_count', len(self.items)))
        return self


class QualitativeItem(StrictModel):
    comparison_index: Index
    relation: Literal['similar', 'possible_paraphrase', 'no_clear_relation']
    reason: NonemptyText
    suggestion: NonemptyText


class QualitativeReport(StrictModel):
    items: list[QualitativeItem] = Field(min_length=1)

    @model_validator(mode='after')
    def indices(self, info: ValidationInfo):
        aligned(self.items, (info.context or {}).get('comparison_count', len(self.items)))
        return self


class SimilarityReport(StrictModel):
    quantitative: QuantitativeReport
    qualitative: QualitativeReport

    @model_validator(mode='after')
    def same_comparisons(self):
        aligned(self.qualitative.items, len(self.quantitative.items))
        return self


def validate_report(value, request: SimilarityInput):
    """绑定原始请求数目，拒绝两类报告同时遗漏末尾对照的情况。"""
    return SimilarityReport.model_validate(
        value, context={'comparison_count': len(request.comparison_texts)})
