# Generated by generate_blocks.py; DO NOT EDIT.
"""查重契约权威来源；语义包中的 contracts.py 由同步脚本生成。"""
from typing import Annotated, Literal
from pydantic import Field, ValidationInfo, model_validator
from pydantic_core import PydanticCustomError
from agent_platform.contracts.base import StrictModel
Index = Annotated[int, Field(ge=0)]
NonemptyText = Annotated[str, Field(min_length=1)]

class SimilarityInput(StrictModel):
    target_text: str
    comparison_texts: list[str] = Field(min_length=1)

def aligned(items, count):
    indices = [item.comparison_index for item in items]
    if len(indices) != count or set(indices) != set(range(count)):
        raise PydanticCustomError('index_coverage', 'comparisonIndex 必须唯一且覆盖全部对照索引')

class ParagraphMatch(StrictModel):
    target_paragraph_index: Index
    comparison_paragraph_indices: list[Index] = Field(min_length=1)

    @model_validator(mode='after')
    def unique_indices(self):
        if len(set(self.comparison_paragraph_indices)) != len(self.comparison_paragraph_indices):
            raise PydanticCustomError('duplicate_indices', '对照段落索引不得重复')
        return self

class QuantitativeItem(StrictModel):
    comparison_index: Index
    similarity: float = Field(ge=0, le=1, allow_inf_nan=False)
    matched_target_characters: int = Field(ge=0)
    total_target_characters: int = Field(gt=0)
    matches: list[ParagraphMatch]

    @model_validator(mode='after')
    def valid_counts(self):
        if self.matched_target_characters > self.total_target_characters:
            raise PydanticCustomError('count_exceeds_total', '匹配字符数不得超过目标字符数')
        positions = [match.target_paragraph_index for match in self.matches]
        if len(set(positions)) != len(positions):
            raise PydanticCustomError('duplicate_position', '每个目标段落位置最多匹配一次')
        return self

class QuantitativeReport(StrictModel):
    method: Literal['paragraph-exact-v1']
    items: list[QuantitativeItem] = Field(min_length=1)

    @model_validator(mode='after')
    def indices(self, info: ValidationInfo):
        aligned(self.items, (info.context or {}).get('comparison_count', len(self.items)))
        return self

class QualitativeItem(StrictModel):
    comparison_index: Index
    relation: Literal['similar', 'possible_paraphrase', 'no_clear_relation']
    reason: NonemptyText
    suggestion: NonemptyText

class QualitativeReport(StrictModel):
    items: list[QualitativeItem] = Field(min_length=1)

    @model_validator(mode='after')
    def indices(self, info: ValidationInfo):
        aligned(self.items, (info.context or {}).get('comparison_count', len(self.items)))
        return self

class SimilarityReport(StrictModel):
    quantitative: QuantitativeReport
    qualitative: QualitativeReport

    @model_validator(mode='after')
    def same_comparisons(self):
        aligned(self.qualitative.items, len(self.quantitative.items))
        return self
from agent_platform.blocks import block

class PreparedTexts(StrictModel):
    target_paragraphs: list[NonemptyText] = Field(min_length=1)
    comparison_paragraphs: list[list[NonemptyText]] = Field(min_length=1)

import re
import unicodedata
from agent_platform.contracts.errors import ErrorResponse, PlatformError
@block(id='similarity-clean', version='1.0.0', name='查重清洗', description='NFC、换行与水平空白规范；拒绝清洗后空文本', dependencies=['pydantic-core>=2,<3'])
def run(value: SimilarityInput) -> PreparedTexts:
    result = []
    for index, text in enumerate([value.target_text, *value.comparison_texts]):
        text = unicodedata.normalize('NFC', text.replace('\r\n', '\n').replace('\r', '\n'))
        parts = [clean for line in text.split('\n') if (clean := re.sub(r'[^\S\r\n\v\f\x85\u2028\u2029]+', ' ', line).strip())]
        if not parts:
            raise PlatformError(ErrorResponse(code='CONTRACT_VALIDATION_ERROR', stage='similarity.preprocess', message='清洗后文本不得为空', field_path=['targetText'] if index == 0 else ['comparisonTexts', index-1]), 422)
        result.append(parts)
    return PreparedTexts(target_paragraphs=result[0], comparison_paragraphs=result[1:])
