# Generated by sync_contracts.py; DO NOT EDIT.
"""模板业务契约；使用 sync_contracts.py 同步到独立包。"""
from pydantic import Field
from agent_platform.contracts.base import StrictModel


class Message(StrictModel):
    text: str = Field(min_length=1)
